"""Bronze/Silver/Gold export/reporting tables — applied verbatim from the DDL a
colleague shared. This is a DERIVED/EXPORT layer, not the system of record: our
page-level schema from migration 0001 remains canonical (see docs/DECISIONS.md #17 and
docs/ARCHITECTURE.md's "Bronze/Silver/Gold export layer" section for why, and for the
sync mapping — chunk-level page_range strings here can't support exact-page citation on
their own). The sync logic that populates these tables from our schema is Phase 5+ work,
not built yet; this migration only creates the tables so the shape exists.

Do not redesign this schema — if it needs to change, that's a conversation with whoever
owns it downstream, not a unilateral edit here.

Tables use `CREATE TABLE IF NOT EXISTS` (the only deviation from the colleague's DDL
verbatim) — the shared dev database already had `company_master_profile` (with data)
created independently before this migration first ran against it. Column/type/constraint
definitions are unchanged; this only guards against re-creation.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-16

"""
from typing import Sequence, Union

from alembic import op

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DDL = """
-- ============================================================================
-- 1. COMPANY MASTER PROFILE (The "Company Brain" / MDM)
-- Stores the unified JSON representation of the company's capabilities.
-- ============================================================================
CREATE TABLE IF NOT EXISTS company_master_profile (
    company_id SERIAL PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    profile_data JSONB NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 2. BRONZE LAYER (Raw Tender Ingestion)
-- Stores the raw, unstructured text extracted from the Tender PDF in chunks.
-- ============================================================================
CREATE TABLE IF NOT EXISTS tender_bronze_raw (
    bronze_chunk_id SERIAL PRIMARY KEY,
    tender_id VARCHAR(255) NOT NULL,   -- A unique ID for the uploaded PDF (e.g., "TENDER-123")
    company_id INT NOT NULL REFERENCES company_master_profile(company_id) ON DELETE CASCADE,
    chunk_sequence INT NOT NULL,       -- Order of the chunk (1, 2, 3...)
    page_range VARCHAR(50),            -- e.g., "Pages 1-20"
    raw_text TEXT NOT NULL,            -- The messy text extracted by PyMuPDF
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 3. SILVER LAYER (Structured Tender Facts)
-- Stores the clean JSON facts extracted from the Bronze chunks by the cheap AI.
-- ============================================================================
CREATE TABLE IF NOT EXISTS tender_silver_extracted (
    silver_fact_id SERIAL PRIMARY KEY,
    tender_id VARCHAR(255) NOT NULL,
    bronze_chunk_id INT NOT NULL REFERENCES tender_bronze_raw(bronze_chunk_id) ON DELETE CASCADE,
    company_id INT NOT NULL REFERENCES company_master_profile(company_id) ON DELETE CASCADE,
    -- This JSONB column holds what the AI found (e.g., {"min_turnover": 50000000, "cert_required": "ISO 9001"})
    extracted_requirements JSONB NOT NULL,
    extracted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 4. GOLD LAYER (Final Go/No-Go & Risk Matrix)
-- Stores the final judgment comparing Silver Requirements vs Company Profile.
-- ============================================================================
CREATE TABLE IF NOT EXISTS tender_gold_analysis (
    gold_analysis_id SERIAL PRIMARY KEY,
    tender_id VARCHAR(255) NOT NULL UNIQUE, -- One final report per tender
    company_id INT NOT NULL REFERENCES company_master_profile(company_id) ON DELETE CASCADE,
    -- FINAL OUTPUTS GENERATED BY ADVANCED AI
    go_nogo_status VARCHAR(50) NOT NULL,    -- 'GO', 'NO_GO', or 'CONDITIONAL_GO'
    go_nogo_score INT,                      -- 0 to 100 confidence score
    match_report JSONB NOT NULL,            -- JSON detailing what matched and what failed
    document_roadmap JSONB,                 -- JSON checklist of documents needed to submit the bid
    risk_matrix JSONB,                      -- JSON list of penalty clauses and risks
    evaluated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

DROP_ALL = """
DROP TABLE IF EXISTS tender_gold_analysis;
DROP TABLE IF EXISTS tender_silver_extracted;
DROP TABLE IF EXISTS tender_bronze_raw;
DROP TABLE IF EXISTS company_master_profile;
"""


def upgrade() -> None:
    op.execute(DDL)


def downgrade() -> None:
    op.execute(DROP_ALL)
